services:
  - type: web
    name: purchase-assistant-api
    env: docker
    plan: free
    healthCheckPath: /docs  # Using FastAPI's docs endpoint as health check
    buildCommand: docker build -t purchase-assistant-api .
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SERVICE_TYPE
        value: "backend"
      - key: RENDER
        value: "true"
      - key: COMPANY_DB_URL
        value: ${COMPANY_DB_URL}  # Will be set in Render dashboard
      - key: APP_DB_URL
        value: ${APP_DB_URL}  # Will be set in Render dashboard
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}  # This will be replaced with your actual API key in Render
    autoDeploy: true

  - type: web
    name: purchase-assistant-ui
    env: docker
    plan: free
    healthCheckPath: /  # Gradio's root path
    buildCommand: docker build -t purchase-assistant-ui .
    envVars:
      - key: API_URL
        value: https://purchase-assistant-api.onrender.com/api/v1  # Points to the API service
      - key: PORT
        value: 7860
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SERVICE_TYPE
        value: "frontend"
      - key: RENDER
        value: "true"
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}  # This will be replaced with your actual API key in Render
    autoDeploy: true

databases:
  - name: purchase-assistant-company-db
    databaseName: purchase_db  # Using our preferred name
    user: company_user
    plan: free

  - name: purchase-assistant-app-db
    databaseName: app_db  # Using our preferred name
    user: app_user
    plan: free 