services:
  - type: web
    name: purchase-assistant-api
    env: docker
    plan: free
    healthCheckPath: /docs  # Using FastAPI's docs endpoint as health check
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SERVICE_TYPE
        value: "backend"
      - key: COMPANY_DB_URL
        fromDatabase:
          name: purchase-assistant-company-db
          property: connectionString
      - key: APP_DB_URL
        fromDatabase:
          name: purchase-assistant-app-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: true  # This will sync from your local environment
    autoDeploy: true

  - type: web
    name: purchase-assistant-ui
    env: docker
    plan: free
    healthCheckPath: /  # Gradio's root path
    envVars:
      - key: API_URL
        value: https://purchase-assistant-api.onrender.com/api/v1  # Points to the API service
      - key: PORT
        value: 7860
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SERVICE_TYPE
        value: "frontend"
      - key: OPENAI_API_KEY
        sync: true  # This will sync from your local environment
    autoDeploy: true

databases:
  - name: purchase-assistant-company-db
    databaseName: purchase_db
    user: company_user
    plan: free

  - name: purchase-assistant-app-db
    databaseName: app_db
    user: app_user
    plan: free 