"""Initial app database migration

Revision ID: 8c90333627f4
Revises: 
Create Date: 2025-05-31 18:37:33.241271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c90333627f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_request_id', sa.Integer(), nullable=False),
    sa.Column('approver_name', sa.String(length=100), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approval_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_request_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feedback_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('app_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('setting_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='app_settings_pkey')
    )
    op.drop_table('user_feedback')
    op.drop_table('purchase_approvals')
    op.drop_table('application_logs')
    # ### end Alembic commands ###
